### ISSUE TITLE
rimozione intestazione e numero di pagina 

### ISSUE THREAD

**Issue by omniavis-ict** [omniavis-ict/codice_appalti#1]
esempio di numero di pagina 
—  5  —

esempio di intestazione: 
Supplemento ordinario n. 12/L  alla GAZZETTA UFFICIALE Serie generale - n. 77 31-3-2023

**Comment by scarsellifi** [comment]
risolto: 86c47813e3e9f3abd36ad70b1d484df97d1bee55
